[theme]
base = "light"
primaryColor = "#1F3864"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#fafafa"
textColor = "#1f2937"
font = "sans serif"

[server]
runOnSave = true
headless = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showSidebarNavigation = true
